// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: devices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner             string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	PublicKey         string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Connected         bool                   `protobuf:"varint,6,opt,name=connected,proto3" json:"connected,omitempty"`
	LastHandshakeTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"`
	ReceiveBytes      int64                  `protobuf:"varint,8,opt,name=receive_bytes,json=receiveBytes,proto3" json:"receive_bytes,omitempty"`
	TransmitBytes     int64                  `protobuf:"varint,9,opt,name=transmit_bytes,json=transmitBytes,proto3" json:"transmit_bytes,omitempty"`
	Endpoint          string                 `protobuf:"bytes,10,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	OwnerName         string                 `protobuf:"bytes,11,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerEmail        string                 `protobuf:"bytes,12,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerProvider     string                 `protobuf:"bytes,13,opt,name=owner_provider,json=ownerProvider,proto3" json:"owner_provider,omitempty"`
	PresharedKey      string                 `protobuf:"bytes,14,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Device) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Device) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Device) GetLastHandshakeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshakeTime
	}
	return nil
}

func (x *Device) GetReceiveBytes() int64 {
	if x != nil {
		return x.ReceiveBytes
	}
	return 0
}

func (x *Device) GetTransmitBytes() int64 {
	if x != nil {
		return x.TransmitBytes
	}
	return 0
}

func (x *Device) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Device) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Device) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *Device) GetOwnerProvider() string {
	if x != nil {
		return x.OwnerProvider
	}
	return ""
}

func (x *Device) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

type AddDeviceReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey          string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey       string                 `protobuf:"bytes,3,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	ManualIpAssignment bool                   `protobuf:"varint,4,opt,name=manual_ip_assignment,json=manualIpAssignment,proto3" json:"manual_ip_assignment,omitempty"`
	ManualIpv4Address  string                 `protobuf:"bytes,5,opt,name=manual_ipv4_address,json=manualIpv4Address,proto3" json:"manual_ipv4_address,omitempty"`
	ManualIpv6Address  string                 `protobuf:"bytes,6,opt,name=manual_ipv6_address,json=manualIpv6Address,proto3" json:"manual_ipv6_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddDeviceReq) Reset() {
	*x = AddDeviceReq{}
	mi := &file_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceReq) ProtoMessage() {}

func (x *AddDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeviceReq.ProtoReflect.Descriptor instead.
func (*AddDeviceReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{1}
}

func (x *AddDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDeviceReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddDeviceReq) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *AddDeviceReq) GetManualIpAssignment() bool {
	if x != nil {
		return x.ManualIpAssignment
	}
	return false
}

func (x *AddDeviceReq) GetManualIpv4Address() string {
	if x != nil {
		return x.ManualIpv4Address
	}
	return ""
}

func (x *AddDeviceReq) GetManualIpv6Address() string {
	if x != nil {
		return x.ManualIpv6Address
	}
	return ""
}

type ListDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesReq) Reset() {
	*x = ListDevicesReq{}
	mi := &file_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesReq) ProtoMessage() {}

func (x *ListDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesReq.ProtoReflect.Descriptor instead.
func (*ListDevicesReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{2}
}

type ListDevicesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Device              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRes) Reset() {
	*x = ListDevicesRes{}
	mi := &file_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRes) ProtoMessage() {}

func (x *ListDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRes.ProtoReflect.Descriptor instead.
func (*ListDevicesRes) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesRes) GetItems() []*Device {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteDeviceReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// admin's may delete a device owned
	// by someone other than the current user
	// if empty, defaults to the current user
	Owner         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceReq) Reset() {
	*x = DeleteDeviceReq{}
	mi := &file_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceReq) ProtoMessage() {}

func (x *DeleteDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceReq.ProtoReflect.Descriptor instead.
func (*DeleteDeviceReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDeviceReq) GetOwner() *wrapperspb.StringValue {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ListAllDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllDevicesReq) Reset() {
	*x = ListAllDevicesReq{}
	mi := &file_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllDevicesReq) ProtoMessage() {}

func (x *ListAllDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllDevicesReq.ProtoReflect.Descriptor instead.
func (*ListAllDevicesReq) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{5}
}

type ListAllDevicesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Device              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllDevicesRes) Reset() {
	*x = ListAllDevicesRes{}
	mi := &file_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllDevicesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllDevicesRes) ProtoMessage() {}

func (x *ListAllDevicesRes) ProtoReflect() protoreflect.Message {
	mi := &file_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllDevicesRes.ProtoReflect.Descriptor instead.
func (*ListAllDevicesRes) Descriptor() ([]byte, []int) {
	return file_devices_proto_rawDescGZIP(), []int{6}
}

func (x *ListAllDevicesRes) GetItems() []*Device {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_devices_proto protoreflect.FileDescriptor

const file_devices_proto_rawDesc = "" +
	"\n" +
	"\rdevices.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x04\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tconnected\x18\x06 \x01(\bR\tconnected\x12J\n" +
	"\x13last_handshake_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHandshakeTime\x12#\n" +
	"\rreceive_bytes\x18\b \x01(\x03R\freceiveBytes\x12%\n" +
	"\x0etransmit_bytes\x18\t \x01(\x03R\rtransmitBytes\x12\x1a\n" +
	"\bendpoint\x18\n" +
	" \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"owner_name\x18\v \x01(\tR\townerName\x12\x1f\n" +
	"\vowner_email\x18\f \x01(\tR\n" +
	"ownerEmail\x12%\n" +
	"\x0eowner_provider\x18\r \x01(\tR\rownerProvider\x12#\n" +
	"\rpreshared_key\x18\x0e \x01(\tR\fpresharedKey\"\xf8\x01\n" +
	"\fAddDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x03 \x01(\tR\fpresharedKey\x120\n" +
	"\x14manual_ip_assignment\x18\x04 \x01(\bR\x12manualIpAssignment\x12.\n" +
	"\x13manual_ipv4_address\x18\x05 \x01(\tR\x11manualIpv4Address\x12.\n" +
	"\x13manual_ipv6_address\x18\x06 \x01(\tR\x11manualIpv6Address\"\x10\n" +
	"\x0eListDevicesReq\"5\n" +
	"\x0eListDevicesRes\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.proto.DeviceR\x05items\"Y\n" +
	"\x0fDeleteDeviceReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05owner\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05owner\"\x13\n" +
	"\x11ListAllDevicesReq\"8\n" +
	"\x11ListAllDevicesRes\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.proto.DeviceR\x05items2\x85\x02\n" +
	"\aDevices\x121\n" +
	"\tAddDevice\x12\x13.proto.AddDeviceReq\x1a\r.proto.Device\"\x00\x12=\n" +
	"\vListDevices\x12\x15.proto.ListDevicesReq\x1a\x15.proto.ListDevicesRes\"\x00\x12@\n" +
	"\fDeleteDevice\x12\x16.proto.DeleteDeviceReq\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x0eListAllDevices\x12\x18.proto.ListAllDevicesReq\x1a\x18.proto.ListAllDevicesRes\"\x00B5Z3github.com/freifunkMUC/wg-access-server/proto/protob\x06proto3"

var (
	file_devices_proto_rawDescOnce sync.Once
	file_devices_proto_rawDescData []byte
)

func file_devices_proto_rawDescGZIP() []byte {
	file_devices_proto_rawDescOnce.Do(func() {
		file_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)))
	})
	return file_devices_proto_rawDescData
}

var file_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_devices_proto_goTypes = []any{
	(*Device)(nil),                 // 0: proto.Device
	(*AddDeviceReq)(nil),           // 1: proto.AddDeviceReq
	(*ListDevicesReq)(nil),         // 2: proto.ListDevicesReq
	(*ListDevicesRes)(nil),         // 3: proto.ListDevicesRes
	(*DeleteDeviceReq)(nil),        // 4: proto.DeleteDeviceReq
	(*ListAllDevicesReq)(nil),      // 5: proto.ListAllDevicesReq
	(*ListAllDevicesRes)(nil),      // 6: proto.ListAllDevicesRes
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 8: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_devices_proto_depIdxs = []int32{
	7, // 0: proto.Device.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: proto.Device.last_handshake_time:type_name -> google.protobuf.Timestamp
	0, // 2: proto.ListDevicesRes.items:type_name -> proto.Device
	8, // 3: proto.DeleteDeviceReq.owner:type_name -> google.protobuf.StringValue
	0, // 4: proto.ListAllDevicesRes.items:type_name -> proto.Device
	1, // 5: proto.Devices.AddDevice:input_type -> proto.AddDeviceReq
	2, // 6: proto.Devices.ListDevices:input_type -> proto.ListDevicesReq
	4, // 7: proto.Devices.DeleteDevice:input_type -> proto.DeleteDeviceReq
	5, // 8: proto.Devices.ListAllDevices:input_type -> proto.ListAllDevicesReq
	0, // 9: proto.Devices.AddDevice:output_type -> proto.Device
	3, // 10: proto.Devices.ListDevices:output_type -> proto.ListDevicesRes
	9, // 11: proto.Devices.DeleteDevice:output_type -> google.protobuf.Empty
	6, // 12: proto.Devices.ListAllDevices:output_type -> proto.ListAllDevicesRes
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_devices_proto_init() }
func file_devices_proto_init() {
	if File_devices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devices_proto_rawDesc), len(file_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devices_proto_goTypes,
		DependencyIndexes: file_devices_proto_depIdxs,
		MessageInfos:      file_devices_proto_msgTypes,
	}.Build()
	File_devices_proto = out.File
	file_devices_proto_goTypes = nil
	file_devices_proto_depIdxs = nil
}
